import {useState} from 'react';
import {useRouter} from 'next/router';
import {gql, useLazyQuery} from '@apollo/client';
import Head from 'next/head';

export const ALL_BANK_USERS_QUERY = gql`
  query allBankUsers {
    queryBankUser {
      id
      pin
      name
      balance
      withdrawlLimit
    }
  }
`;

export const GET_BANK_USER_BY_PIN = gql`
  query GetBankUserByPin($pin: Int!) {
    queryBankUser(filter: {pin: {in: [$pin]}}) {
      id
    }
  }
`;

export default function Home() {
  const [searchPin, setSearchPin] = useState(0);
  const [bankUser, setBankUser] = useState(null);
  const [inputError, setInputError] = useState(false);

  const router = useRouter();

  const [getBankUser, {loading, error, data}] =
    useLazyQuery(GET_BANK_USER_BY_PIN);

  function handlePinInput(e) {
    setSearchPin(Number(e.target.value));
  }

  async function onPINSubmit(e) {
    e.preventDefault();
    setInputError(false);
    const user = await getBankUser({variables: {pin: searchPin}});
    console.log(user);
    if (user?.data?.queryBankUser.length === 0) {
      setInputError(true);
      return;
    }

    const id = user?.data?.queryBankUser[0]?.id;

    router.push({
      pathname: '/dashboard',
      query: {
        id,
      },
    });
  }

  return (
    <>
      <Head>
        <title>JTM - JMONEY Automated Transfer Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="pinWrap">
          <form onSubmit={onPINSubmit}>
            <input
              placeholder="Enter your 4 Digit PIN"
              onChange={handlePinInput}
              maxLength={4}
              type="number"
            />
            <button type="submit">Enter</button>
            {data &&
              data.queryBankUser.length >= 1 &&
              `${data.queryBankUser[0].name}`}
            {inputError && <div>The PIN you entered is invalid.</div>}
            {loading && 'Is Loading'}
          </form>
        </div>
      </main>
    </>
  );
}
