import {useState, useRef} from 'react';
import {useRouter} from 'next/router';
import {useLazyQuery} from '@apollo/client';
import Head from 'next/head';
import {Header} from '../components/header';
import {GET_BANK_USER_BY_PIN} from '../lib/queries';
import {LoadingOutlined, WarningOutlined} from '@ant-design/icons';

export default function Home() {
  const [searchPin, setSearchPin] = useState(0);
  const [inputError, setInputError] = useState(false);

  const router = useRouter();

  const [getBankUser, {loading, error, data}] =
    useLazyQuery(GET_BANK_USER_BY_PIN);

  function handlePinInput(e) {
    setSearchPin(Number(e.target.value));
  }

  async function onPINSubmit(e) {
    e.preventDefault();
    setInputError(false);
    const user = await getBankUser({variables: {pin: searchPin}});
    if (user?.data?.queryBankUser.length === 0) {
      setInputError(true);
      return;
    }

    const id = user?.data?.queryBankUser[0]?.id;

    router.push({
      pathname: '/dashboard',
      query: {
        id,
      },
    });
  }

  return (
    <>
      <Head>
        <title>JTM - JMONEY Automated Transfer Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="container">
          <div className="pinWrap actionForm">
            <h1>Welcome Back!</h1>
            <p>To begin, enter your four digit PIN</p>
            <form onSubmit={onPINSubmit}>
              <input
                placeholder="Enter your 4 Digit PIN"
                onChange={handlePinInput}
                maxLength={4}
                type="text"
              />
              <button type="submit">
                {loading ? <LoadingOutlined /> : 'Enter'}
              </button>
              <div className="warning">
                {inputError && (
                  <>
                    <WarningOutlined /> The PIN you entered is invalid.
                  </>
                )}
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
